### ISSUE TITLE
Dart 2 support

### ISSUE THREAD

**Issue by d-scheck** [macif-dev/sslpinning_plugin#2]
It looks like version 1.0 version has Dart 2 support, but it doesn't look like it was released to the Pub site: https://pub.dev/packages/ssl_pinning_plugin#-installing-tab-

Are there plans to release 1.0?

**Comment by us3soap** [comment]
Hi, we have published this plugin on version 1.1 today with compatibility Dart2.

Tell us if you have any problems with this plugin.
